;;; SPDX-License-Identifier: LGPL-3.0-or-later
;;;
;;; NeoForge - Z80 sound driver for the V ROM test
;;;
;;; Derived from ngdevkit-examples' base-sound-driver.s and user_commands.s,
;;; Copyright (c) 2020-2026 Damien Ciabrini, LGPL-3.0-or-later. This file
;;; inherits that licence. See ../LICENSE.md.
;;;
;;; Unlike ../rom/sound-driver.s, this one actually plays something. It adds
;;; a single user command that starts one ADPCM-A sample on channel 1.
;;;
;;; On linking -aes: nullsound's two variants differ only in fm-tables.inc and
;;; ssg-tables.inc, and only entrypoint.s is assembled per-variant. ADPCM-A
;;; playback does not use those tables at all - its rate is fixed by the
;;; YM2610's own clock - so the variant makes no difference to *this* ROM even
;;; though it does play a sound. It will matter the moment anything here uses
;;; FM or SSG. `[VERIFIED: ngdevkit nullsound/Makefile.in, OBJS vs OBJS_AES]`
;;;
;;; What is being tested is not the YM2610 - that is on the motherboard and
;;; is not ours to doubt. It is the path from the cartridge's V ROM to it:
;;; the sample data lives on the cart, crosses the connector on its own bus,
;;; and is fetched by the YM2610 during playback. A cartridge that cannot
;;; serve those reads produces silence, and no other test we have would
;;; notice.

        .include "helpers.inc"

        .area   CODE

;;; See ../rom/sound-driver.s for why entry 2 is a plain `ret` and not a jump
;;; to snd_command_unused. Same reasoning, same trap.

cmd_jmptable::
        jp      snd_command_unused                      ; 00 unused
        jp      snd_command_01_prepare_for_rom_switch   ; 01 wait in RAM
        jp      no_eye_catcher                          ; 02 post-init hook
        jp      snd_command_03_reset_driver             ; 03 reset driver
        jp      play_chirp                              ; 04 our one command
        init_unused_cmd_jmptable                        ; 05..7f -> unused

;;; Must follow the padding macro - it sizes itself from the distance back
;;; to cmd_jmptable.
no_eye_catcher:
        ret

play_chirp:
        ld      ix, #adpcm_a_chirp
        call    snd_adpcm_a_play
        ret


;;; ADPCM-A sample descriptor
;;;
;;; Seven bytes, the layout nullsound's snd_adpcm_a_play expects in IX. The
;;; start and stop offsets are the sample's position in the V ROM, in units
;;; of 256 bytes - which is the granularity the YM2610's own address
;;; registers work in. samples.inc is generated by vromtool.py from
;;; samples.yaml, so these never have to be worked out by hand or kept in
;;; sync when the sample changes length.

        .include "samples.inc"

adpcm_a_chirp:
        .db     CHIRP_START_LSB
        .db     CHIRP_START_MSB
        .db     CHIRP_STOP_LSB
        .db     CHIRP_STOP_MSB
        .db     0                       ; channel index (0 = channel 1)
        .db     0xdf                    ; both speakers, maximum volume
        .db     1                       ; channel bit mask for channel 1
